### ISSUE TITLE
Не получается войти в базу данных(с помощью database navigator)

### ISSUE THREAD

**Issue by Serg5858** [Serg5858/diploma#3]
Запускаю докер.
Запускаю в идее doker-compose up
Запускаю приложение командой  java "-Dspring.datasource-postgresql.url=jdbc:postgresql://localhost:5432/app" -jar artifacts/aqa-shop.jar
Захожу в DB Browser.  
Вижу там такую таблицу.
![17 11 идея бд](https://user-images.githubusercontent.com/101870270/203059575-8940d6b8-5854-4b70-b1f8-da702d0aa584.png)
вижу таблицы в схемах,но не могу в них зайти и посмотреть колонки в ней.
![таблицы в схемах,но не могу зайти в БД](https://user-images.githubusercontent.com/101870270/203060151-0a41d2a0-f284-477b-af5b-e56a8d516d2e.png)
Что я делаю не так?

**Comment by ArRomanov** [comment]
таблицы должны быть в схеме public
