### ISSUE TITLE
Через DB Navigator не могу зайти в базу данных

### ISSUE THREAD

**Issue by Serg5858** [Serg5858/diploma#4]
Касаемо postgresql удалось подключится, но не могу зайти в таблицы и консоль. Причем вчера консоль открывалась, сегодня уже нет.
![122 11 соединение  проходит ,но открыть консоль и таблицы не могу](https://user-images.githubusercontent.com/101870270/203299719-d7473306-30d1-4bab-8a82-48fdceddca95.png)
![222 11 PG не открывается (возможно дело в настройках)](https://user-images.githubusercontent.com/101870270/203299879-8e7f47b2-6335-4970-bb4f-1071c538b99f.png)
По mysql не получилось установить соединение, убрал из application.properties строку с настройками-результат тот же.
![322 11 mysql не подключается совсем](https://user-images.githubusercontent.com/101870270/203300312-b97de3f1-087e-417b-a440-d382e095dc82.png)
Пытался удалить это соединение, но оно потом снова появляется в settings в DB Navigator.Test connection не проходит.
![422 11 mysql не подкл., пробовал по-разному](https://user-images.githubusercontent.com/101870270/203300563-913be1b4-3d87-4932-bafb-e60e028c7e3d.png)
не думаю, чтобы каждый раз нужно было по-новому подключаться к БД(пробовал-безрезультатно).
1)Возможно ли сделать так, чтобы можно было зайти в консоль и открыть таблицы в postgres?
2)И что делаю не так с подключением mysql?

**Comment by ArRomanov** [comment]
1. при подключении в ide поле database должно заполняться названиями БД, которые вы создали - тут https://github.com/Serg5858/diploma/blob/main/docker-compose.yml#L9 и тут https://github.com/Serg5858/diploma/blob/main/docker-compose.yml#L19. Логины и пароли из того же файла
2. Судя по скринам у вас таблицы не создались. Они должны создаваться при корректном запуске приложения. Как вы запускаете приложение?
